# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7636c1c14424bfbe2267b2b8f8d07ec65c3a127043e71769d0b114725d938aefdc69ddb694492ac6d50526a03c09c8cc87001bd93eb5b994fcca0cf9a4e1f4d

test:
  secret_key_base: d819b5504621298d9c4a5e9730e860b8efbbff2c74c2c2c58cbbf122829f8d7b218b2381e5d25659aa01555e77b12df0e4de8fc47c337b8c3912c975d98f97f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
